apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: matrixflow
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: matrixflow-erp
spec:
  accessModes:
    - ReadWriteOnce
  # NOTE: storageClassName 可根据实际环境配置，如 gp3、standard、local-path 等
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
