import { Injectable, Logger, UnauthorizedException, BadRequestException } from '@nestjs/common'
import { ConfigService } from '@nestjs/config'
import { PrismaService } from '../../prisma/prisma.service'
import { RedisService } from '../../redis/redis.service'
import axios from 'axios'
import * as crypto from 'crypto'

/** Authing OIDC 返回的用户信息 */
export interface AuthingUserInfo {
  sub: string // Authing 用户唯一 ID
  name?: string
  nickname?: string
  picture?: string
  email?: string
  phone_number?: string
  external_id?: string
}

@Injectable()
export class AuthingService {
  private readonly logger = new Logger(AuthingService.name)
  private readonly appId: string
  private readonly appSecret: string
  private readonly host: string
  private readonly redirectUri: string
  private readonly enabled: boolean

  constructor(
    private readonly configService: ConfigService,
    private readonly prisma: PrismaService,
    private readonly redis: RedisService,
  ) {
    this.appId = this.configService.get<string>('AUTHING_APP_ID') || ''
    this.appSecret = this.configService.get<string>('AUTHING_APP_SECRET') || ''
    this.host = this.configService.get<string>('AUTHING_HOST') || ''
    this.redirectUri =
      this.configService.get<string>('AUTHING_REDIRECT_URI') || 'https://ddddkiii.com/auth/callback'
    this.enabled = !!(this.appId && this.appSecret && this.host)

    if (this.enabled) {
      this.logger.log(`Authing 集成已启用，host: ${this.host}`)
    } else {
      this.logger.warn('Authing 未配置完整，微信/手机号登录将不可用')
    }
  }

  /** 是否已启用 Authing */
  isEnabled(): boolean {
    return this.enabled
  }

  /**
   * 生成 Authing OIDC 授权 URL
   * @param state Custom state for CSRF protection (generated by caller)
   */
  getAuthorizeUrl(state: string): string {
    if (!this.enabled) {
      throw new BadRequestException('Authing 未配置')
    }

    const params = new URLSearchParams({
      client_id: this.appId,
      redirect_uri: this.redirectUri,
      response_type: 'code',
      scope: 'openid profile email phone',
      state,
      prompt: 'login',
    })

    return `https://${this.host}/oidc/auth?${params.toString()}`
  }

  /**
   * 生成 CSRF state 并存入 Redis（10 分钟过期）
   */
  async generateState(): Promise<string> {
    const state = crypto.randomBytes(16).toString('hex')
    await this.redis.setWithTTL(`authing:state:${state}`, '1', 600)
    return state
  }

  /**
   * 验证 state 是否有效，验证后删除
   */
  async validateState(state: string): Promise<boolean> {
    const exists = await this.redis.exists(`authing:state:${state}`)
    if (exists) {
      await this.redis.del(`authing:state:${state}`)
      return true
    }
    return false
  }

  /**
   * 用授权码换取 access_token，再获取用户信息
   */
  async exchangeCodeForUserInfo(code: string, state: string): Promise<AuthingUserInfo> {
    // 1. 验证 state
    const stateValid = await this.validateState(state)
    if (!stateValid) {
      throw new UnauthorizedException('无效的 state 参数，可能存在 CSRF 攻击')
    }

    // 2. 用 code 换 access_token
    const tokenUrl = `https://${this.host}/oidc/token`
    let accessToken: string

    try {
      const tokenRes = await axios.post(
        tokenUrl,
        new URLSearchParams({
          grant_type: 'authorization_code',
          client_id: this.appId,
          client_secret: this.appSecret,
          code,
          redirect_uri: this.redirectUri,
        }),
        {
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
          timeout: 10000,
        },
      )
      accessToken = tokenRes.data.access_token
    } catch (error) {
      this.logger.error(
        `Authing token 交换失败: ${axios.isAxiosError(error) ? error.response?.data : error}`,
      )
      throw new UnauthorizedException('Authing 授权码无效或已过期')
    }

    if (!accessToken) {
      throw new UnauthorizedException('Authing 未返回 access_token')
    }

    // 3. 用 access_token 获取用户信息
    const userinfoUrl = `https://${this.host}/oidc/me`
    try {
      const userinfoRes = await axios.get<AuthingUserInfo>(userinfoUrl, {
        headers: { Authorization: `Bearer ${accessToken}` },
        timeout: 10000,
      })
      return userinfoRes.data
    } catch (error) {
      this.logger.error(
        `Authing 获取用户信息失败: ${axios.isAxiosError(error) ? error.response?.data : error}`,
      )
      throw new UnauthorizedException('获取 Authing 用户信息失败')
    }
  }

  /**
   * 根据 Authing 用户信息查找或创建本地用户
   */
  async findOrCreateUser(authingUser: AuthingUserInfo) {
    const authingUserId = authingUser.sub

    // 1. 尝试通过 authingUserId 查找已有用户
    let user = await this.prisma.user.findUnique({
      where: { authingUserId },
    })

    if (user) {
      // 已存在，更新最后登录时间
      await this.prisma.user.update({
        where: { id: user.id },
        data: {
          lastLoginAt: new Date(),
          avatar: authingUser.picture || user.avatar,
          name: authingUser.nickname || authingUser.name || user.name,
        },
      })
      this.logger.log(`Authing 用户登录: ${user.id}`)
      return user
    }

    // 2. 新用户 — 自动创建
    const name =
      authingUser.nickname ||
      authingUser.name ||
      (authingUser.phone_number
        ? `用户${authingUser.phone_number.slice(-4)}`
        : `用户${authingUserId.slice(-6)}`)

    // 如果有手机号，检查是否已有该手机号的用户（绑定场景）
    if (authingUser.phone_number) {
      const existingByPhone = await this.prisma.user.findUnique({
        where: { phone: authingUser.phone_number },
      })
      if (existingByPhone) {
        // 绑定 Authing ID 到已有用户
        user = await this.prisma.user.update({
          where: { id: existingByPhone.id },
          data: {
            authingUserId,
            lastLoginAt: new Date(),
            avatar: authingUser.picture || existingByPhone.avatar,
          },
        })
        this.logger.log(`Authing 用户绑定到已有账号: ${user.id}`)
        return user
      }
    }

    // 如果有邮箱，检查是否已有该邮箱的用户
    if (authingUser.email) {
      const existingByEmail = await this.prisma.user.findUnique({
        where: { email: authingUser.email },
      })
      if (existingByEmail) {
        user = await this.prisma.user.update({
          where: { id: existingByEmail.id },
          data: {
            authingUserId,
            lastLoginAt: new Date(),
            avatar: authingUser.picture || existingByEmail.avatar,
          },
        })
        this.logger.log(`Authing 用户绑定到已有账号: ${user.id}`)
        return user
      }
    }

    // 创建新用户
    user = await this.prisma.user.create({
      data: {
        email: authingUser.email || null,
        phone: authingUser.phone_number || null,
        password: null,
        name,
        avatar: authingUser.picture || null,
        authingUserId,
        lastLoginAt: new Date(),
      },
    })

    this.logger.log(`Authing 新用户创建: ${user.id} (${name})`)
    return user
  }
}
