CREATE TABLE IF NOT EXISTS "Notification" ("id" TEXT NOT NULL PRIMARY KEY, "type" TEXT NOT NULL, "title" TEXT NOT NULL, "content" TEXT, "read" BOOLEAN NOT NULL DEFAULT false, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "userId" TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS "Notification_userId_idx" ON "Notification"("userId");
CREATE INDEX IF NOT EXISTS "Notification_read_idx" ON "Notification"("read");
CREATE TABLE IF NOT EXISTS "Competitor" ("id" TEXT NOT NULL PRIMARY KEY, "platform" TEXT NOT NULL, "platformUserId" TEXT NOT NULL, "nickname" TEXT NOT NULL, "avatar" TEXT, "bio" TEXT, "followers" INTEGER NOT NULL DEFAULT 0, "note" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "userId" TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS "Competitor_userId_idx" ON "Competitor"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "Competitor_platformUserId_userId_key" ON "Competitor"("platformUserId","userId");
CREATE TABLE IF NOT EXISTS "CompetitorSnapshot" ("id" TEXT NOT NULL PRIMARY KEY, "date" DATE NOT NULL, "followers" INTEGER NOT NULL DEFAULT 0, "views" INTEGER NOT NULL DEFAULT 0, "likes" INTEGER NOT NULL DEFAULT 0, "comments" INTEGER NOT NULL DEFAULT 0, "posts" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "competitorId" TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS "CompetitorSnapshot_competitorId_idx" ON "CompetitorSnapshot"("competitorId");
CREATE TABLE IF NOT EXISTS "AccountGroup" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "color" TEXT NOT NULL DEFAULT '#409EFF', "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "userId" TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS "AccountGroup_userId_idx" ON "AccountGroup"("userId");
CREATE TABLE IF NOT EXISTS "Asset" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "type" TEXT NOT NULL, "url" TEXT NOT NULL, "size" INTEGER NOT NULL DEFAULT 0, "width" INTEGER, "height" INTEGER, "duration" INTEGER, "mimeType" TEXT, "tags" TEXT[], "folderId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "userId" TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS "Asset_userId_idx" ON "Asset"("userId");
CREATE INDEX IF NOT EXISTS "Asset_type_idx" ON "Asset"("type");
